"use client"

import type { BaseMemory, Goal, Reminder } from './types'

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString()
const daysFromNow = (d: number) => new Date(now.getTime() + d * 24 * 60 * 60 * 1000).toISOString()

export const SEED_MEMORIES: BaseMemory[] = [
  {
    id: 'seed-1',
    rootHash: '0xa3f8b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1',
    title: 'First day at the new job',
    content: 'Started my new role as senior engineer. The team is fantastic — everyone was welcoming. Got access to all the systems and met the CTO. Feeling optimistic about what we can build together.',
    tags: ['work', 'career', 'milestone'],
    category: 'career',
    type: 'milestone',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(45),
    pinned: true,
  },
  {
    id: 'seed-2',
    rootHash: '0xb4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5',
    title: 'Decided to learn Spanish',
    content: "Started Duolingo plus a weekly conversation class. Goal is conversational fluency in 12 months. Already know how to say hola and gracias.",
    tags: ['learning', 'language', 'personal-growth'],
    category: 'personal',
    type: 'goal',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: 'seed-3',
    rootHash: '0xc5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
    title: 'Built the MVP in a weekend',
    content: 'Shipped the first working prototype of MyGuy. Integrated 0G storage for the memory layer. The demo worked flawlessly — judges were impressed with the decentralized architecture.',
    tags: ['hackathon', '0g', 'web3', 'milestone'],
    category: 'projects',
    type: 'milestone',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    pinned: true,
  },
  {
    id: 'seed-4',
    rootHash: '0xd6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7',
    title: 'Coffee with Sarah from university',
    content: 'Had a great catch-up with Sarah after 3 years. She just moved back to the city and is working on a climate-tech startup. We agreed to meet monthly.',
    tags: ['friendship', 'university', 'coffee'],
    category: 'relationships',
    type: 'memory',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'seed-5',
    rootHash: '0xe7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8',
    title: 'Completed the marathon',
    content: 'Finished my first marathon in 4:12:37. The last 6 miles were brutal but crossing that finish line was one of the best feelings of my life. Training for 6 months paid off.',
    tags: ['running', 'fitness', 'milestone', 'achievement'],
    category: 'personal',
    type: 'milestone',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
]

export const SEED_GOALS: Goal[] = [
  {
    id: 'seed-goal-1',
    title: 'Launch MyGuy public beta',
    description: 'Polish the product, get user feedback, and launch to the public after the hackathon.',
    status: 'active',
    progress: 65,
    targetDate: daysFromNow(60),
    category: 'projects',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    id: 'seed-goal-2',
    title: 'Spanish fluency in 12 months',
    description: 'Reach B2 level — able to hold full conversations comfortably.',
    status: 'active',
    progress: 15,
    targetDate: daysFromNow(335),
    category: 'personal',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: 'seed-goal-3',
    title: 'Read 24 books this year',
    description: 'Two books per month across different genres.',
    status: 'active',
    progress: 50,
    targetDate: daysFromNow(180),
    category: 'personal',
    createdAt: daysAgo(180),
    updatedAt: daysAgo(5),
  },
]

export const SEED_REMINDERS: Reminder[] = [
  {
    id: 'seed-reminder-1',
    title: 'Call Mom on her birthday',
    description: "Don't forget flowers!",
    dueDate: daysFromNow(3),
    completed: false,
    priority: 'high',
    category: 'relationships',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'seed-reminder-2',
    title: 'Submit 0G Zero Cup project',
    description: 'Final submission for the hackathon.',
    dueDate: daysFromNow(1),
    completed: false,
    priority: 'high',
    category: 'projects',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'seed-reminder-3',
    title: 'Monthly Spanish conversation class',
    description: 'Online session with tutor at 7pm.',
    dueDate: daysFromNow(5),
    completed: false,
    priority: 'medium',
    category: 'personal',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'seed-reminder-4',
    title: 'Review PR for authentication module',
    description: 'Alex opened a PR, needs code review.',
    dueDate: daysFromNow(0),
    completed: false,
    priority: 'medium',
    category: 'career',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
]
